// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHoYE4-HoykjxGpqIJXR9g1i4Tj8_LrCU',
    appId: '1:301936892186:web:6651410813c559bf51b4a3',
    messagingSenderId: '301936892186',
    projectId: 'ask2movie-project',
    authDomain: 'ask2movie-project.firebaseapp.com',
    storageBucket: 'ask2movie-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqRXyn0m33z19ZtrboTiDJ1caJLo-887Y',
    appId: '1:1029458190354:android:459a2dafde8254990038cb',
    messagingSenderId: '1029458190354',
    projectId: 'ask2movie-46970',
    storageBucket: 'ask2movie-46970.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNplaYcTAvwrqm51hHIdgxQIC2JVGtTdo',
    appId: '1:1029458190354:ios:d966235dab6fc87c0038cb',
    messagingSenderId: '1029458190354',
    projectId: 'ask2movie-46970',
    storageBucket: 'ask2movie-46970.appspot.com',
    iosBundleId: 'com.example.ask2movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASD-QVtPns-WnFFnPTnVmQl2VoBT4zkqs',
    appId: '1:301936892186:ios:0d2c224389f071a151b4a3',
    messagingSenderId: '301936892186',
    projectId: 'ask2movie-project',
    storageBucket: 'ask2movie-project.appspot.com',
    iosBundleId: 'com.example.ask2movie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHoYE4-HoykjxGpqIJXR9g1i4Tj8_LrCU',
    appId: '1:301936892186:web:e6c95b804af5a3ee51b4a3',
    messagingSenderId: '301936892186',
    projectId: 'ask2movie-project',
    authDomain: 'ask2movie-project.firebaseapp.com',
    storageBucket: 'ask2movie-project.appspot.com',
  );

}